### ISSUE TITLE
Use embeddings to assemble link prediction classifier for human vs mouse phenotype equivalency.

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-ontoml#6]
- [x] find silver standard mouse <-> human phenotypes - ~~possibly here~~ Nico says [here](https://bbop-ontologies.s3.amazonaws.com/upheno/current/upheno-release/all/upheno_mapping_all.csv)
- [x] make silver/gold standard edge file with mouse <-> human phenotypes (or does this already exist?)

Classifiers to try:
- [ ] random forest
- [ ] MLP
- [ ] #11

In practice, all classifiers may be defined in a single NEAT config after implementing #5

**Comment by justaddcoffee** [comment]
@matentzn we need some mouse <-> human phenotype mappings for this OntoML project, and found [this directory](https://data.monarchinitiative.org/upheno2/current/upheno-release/all/). Can you advise about whether we could use [upheno_mapping_all.csv](https://data-test.monarchinitiative.org/upheno2/current/upheno-release/all/upheno_mapping_all.csv) for this experiment? 

Basically what we need is a gold or silver standard of mouse - human phenotypes in order to train a link prediction classifier. I know you probably explained what each of these files is before and which to use, just making sure we use the right file. Thanks!

**Comment by matentzn** [comment]
Great you are getting to that :)

Upheno at data.mi is outdated, use instead:

https://bbop-ontologies.s3.amazonaws.com/upheno/current/upheno-release/all/upheno_mapping_all.csv

Feel free to also plunder:

https://github.com/mapping-commons/mh_mapping_initiative/tree/master/mappings

Generally, whatever infrastructure you are building should prepare itself for reading mapping files in SSSOM format, like 

https://github.com/mapping-commons/mh_mapping_initiative/blob/master/mappings/mp_hp_impc_eye_embedded.sssom.tsv

**Comment by justaddcoffee** [comment]
Great, thanks Nico!

**Comment by matentzn** [comment]
Whenever you output any mappings from any process, it would be great if you could consider publishing them in SSSOM, so we can process them further :)

**Comment by caufieldjh** [comment]
Absolutely, @matentzn - I decided to split off SSSOM generation/parsing into its own task here, but we'll definitely make them available.
